---
- name: "Ensure history_time_format.sh is set"
  ansible.builtin.copy:
    src: "history_time_format.sh"
    dest: "/etc/profile.d/history_time_format.sh"
    mode: 0644
    owner: root
  when: history_time_format
