---
- name: "Get installed packages"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Remove vim if neovim is installed"
  ansible.builtin.package:
    name: "vim"
    state: "absent"
  when: "'neovim' in ansible_facts.packages"

- name: "Ensure .config/nvim directory exists"
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
  when: "'neovim' in ansible_facts.packages and disable_neovim_mouse_support"

- name: "Check if init.vim exists"
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
  register: init_vim_stat
  when: "'neovim' in ansible_facts.packages and disable_neovim_mouse_support"

- name: "Ensure init.vim exists"
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
  when: "'neovim' in ansible_facts.packages and disable_neovim_mouse_support and not init_vim_stat.stat.exists"

- name: "Disable mouse support in neovim"
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    line: "set mouse="
    state: present
  when: "'neovim' in ansible_facts.packages and disable_neovim_mouse_support"
