---
- name: Get installed packages
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Remove vim if neovim is installed"
  ansible.builtin.package:
    name: "vim"
    state: "absent"
  when: "'neovim' in ansible_facts.packages"
