---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "linux-admin-packages-${image:-centos8}-${tag:-latest}${TOX_ENVNAME}"
    image: geerlingguy/docker-${image:-centos8}-ansible:${tag:-latest}
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
