---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: "linux-admin-packages-${image:-centos8}-${tag:-latest}${TOX_ENVNAME}"
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
