---
name: Release to Ansible Galaxy
on:
  release:
    types: [created, edited, published, released]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.galaxy_api_key }}
          git_branch: main
