---
#
# Ansible managed
#

name: Ansible Molecule
on:
  push:
  pull_request:
  schedule:
    - cron: "47 22 24 * *"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "rockylinux8"
            tag: "latest"
          - image: "centos7"
            tag: "latest"
          - image: "ubuntu1804"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
