---
#
# Ansible managed
#

name: Ansible Molecule
on:
  push:
  pull_request:
  schedule:
    - cron: "47 22 24 * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ubuntu2204
          - ubuntu2004
          - rockylinux9
          - rockylinux8
          - centos7
          - debian11
          - debian10
          - debian9
          - fedora36
          - fedora35
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: "${{ matrix.image }}"
          options: parallel
